# -*- coding: utf-8 -*-
"""clustering_estudiantes_parentales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrSKcDkg8lS84WS2lDNUUs9l_v84UTnR
"""

import pandas as pd
from datetime import datetime
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
from sklearn.feature_selection import SelectKBest, chi2
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import spearmanr


# Load the dataset
file_path = 'dataset_estudiantes_parentales.csv'

# Attempt to read the file, using 'latin1' encoding as a fallback for potential encoding issues
df = pd.read_csv(file_path, sep=";", encoding='latin1')

# Intentar cargar el archivo con utf-8
#df = pd.read_csv('dataset_estudiantes_parentales.csv', sep=";", encoding='utf-8', errors='replace')


# Display the first few rows to visualize the data
print("First few rows of the dataset:")
print(df.head())

# Check for columns with null values
print("\nColumns with null values:")
print(df.isnull().sum())

# Display the number of records
print(f"\nNumero de Registros antes de eliminar nulos: {len(df)}")

# Remove rows with null values
df_cleaned = df.dropna()

# Display the number of records
print(f"\nNumero de Registros despues de eliminar nulos: {len(df_cleaned)}")

'''
# Drop rows where 'carrera' is numeric or empty
if 'carrera' in df_cleaned.columns:
    df_cleaned = df_cleaned[df_cleaned['carrera'].apply(lambda x: isinstance(x, str) and not x.isnumeric() and x.strip() != "")]
'''

# Display the number of records
print(f"\nNumero de Registros despues de eliminar carreras que tengan numeros: {len(df)}")

# Drop the 'edad_hijos' column if it exists
if 'edad_hijos' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['edad_hijos'])

# Drop the 'codigo' column if it exists
if 'codigo' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['codigo'])


# Drop the 'dni' column if it exists
if 'dni' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['dni'])

# Drop the 'id_estudiante' column if it exists
if 'id_estudiante' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['id_estudiante'])

# Calculate the 'edad' column based on the 'f_nacimiento' column
if 'f_nacimiento' in df_cleaned.columns:
    df_cleaned['edad'] = df_cleaned['f_nacimiento'].apply(lambda x: datetime.now().year - pd.to_datetime(x).year)

# Drop the 'f_nacimiento' column if it exists
if 'f_nacimiento' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['f_nacimiento'])

# Drop the 'tiempo_libre' column if it exists
# La columna, tiene datos muy variados, es textual la descripcion
if 'tiempo_libre' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['tiempo_libre'])

'''
# La Data tiene muchos erroes en cuanto al numero de hijos

# Correct invalid data in the 'num_hijos' column if it exists
if 'num_hijos' in df_cleaned.columns:
    # Replace non-numeric values with NaN
    df_cleaned['num_hijos'] = pd.to_numeric(df_cleaned['num_hijos'], errors='coerce')

    # Replace NaN values with the median value
    median_hijos = df_cleaned['num_hijos'].median()
    df_cleaned['num_hijos'].fillna(median_hijos, inplace=True)

    # Identify outliers using the IQR method
    Q1 = df_cleaned['num_hijos'].quantile(0.25)
    Q3 = df_cleaned['num_hijos'].quantile(0.75)
    IQR = Q3 - Q1

    # Filter out outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_cleaned['num_hijos'] = df_cleaned['num_hijos'].apply(lambda x: x if lower_bound <= x <= upper_bound else median_hijos)

    # Ensure all values are integers
    df_cleaned['num_hijos'] = df_cleaned['num_hijos'].round().astype(int)


# Save the cleaned and processed dataset
cleaned_file_path = './dataset_numhijos_corregidos.csv'
df_cleaned.to_csv(cleaned_file_path, index=False)


# Display frequency table for 'num_hijos'
print("\nFrequency table for 'num_hijos':")
freq_table = df_cleaned['num_hijos'].value_counts().sort_index()
print(freq_table)


# Plot frequency distribution
plt.figure(figsize=(8, 6))
freq_table.plot(kind='bar', color='skyblue')
plt.title("Frequency Distribution of 'num_hijos'")
plt.xlabel("Number of Children")
plt.ylabel("Frequency")
plt.xticks(rotation=0)
plt.show()


'''
# Los datos de la cantidad de hijos, no es acorde a las edades que se ponen y la fecha de nacimiento del estudiante padre

# Drop the 'num_hijos' column if it exists
if 'num_hijos' in df_cleaned.columns:
    df_cleaned = df_cleaned.drop(columns=['num_hijos'])

'''

# Display frequency table
print("\nFrequency table':")
freq_table = df_cleaned['carrera'].value_counts().sort_index()
print(freq_table)

# Plot frequency distribution
plt.figure(figsize=(8, 6))
freq_table.plot(kind='bar', color='skyblue')
plt.title("Frequency Distribution ")
plt.xlabel("Carreras")
plt.ylabel("Frequency")
plt.xticks(rotation=0)
plt.show()
'''

'''
# NO ES RELEVANTE

# Adjust 'vive_con' column based on 'genero'
if 'vive_con' in df_cleaned.columns and 'genero' in df_cleaned.columns:
    def ajustar_vive_con(row):
        if row['vive_con'] == 'Solo (a )':
            return 'Solo' if row['genero'] == 'masculino' else 'Sola'
        return row['vive_con']

    df_cleaned['vive_con'] = df_cleaned.apply(ajustar_vive_con, axis=1)

'''

# Ajustar la columna 'carrera' para corregir valores no válidos
if 'carrera' in df_cleaned.columns:
    # Identificar valores no válidos (valores numéricos en este caso)
    invalid_carreras = df_cleaned['carrera'].apply(lambda x: str(x).isdigit())

    # Calcular frecuencia relativa de categorías válidas para imputación ponderada
    valid_carreras = df_cleaned.loc[~invalid_carreras, 'carrera']
    frequencies = valid_carreras.value_counts(normalize=True)

    # Reemplazar valores inválidos de forma aleatoria ponderada
    num_invalid = invalid_carreras.sum()
    df_cleaned.loc[invalid_carreras, 'carrera'] = np.random.choice(
        frequencies.index,
        size=num_invalid,
        p=frequencies.values
    )

df_cleaned.head()

from google.colab import files

# Guardar el archivo limpio
df_cleaned.to_csv('dataset_cleaned.csv', sep=';', index=False, encoding="latin1")

# Descargar el archivo
#files.download('dataset_cleaned.csv')

# Display the number of rows and columns in the cleaned dataframe
print(f"Number of rows in df_cleaned: {df_cleaned.shape[0]}")
print(f"Number of columns in df_cleaned: {df_cleaned.shape[1]}")

df_cleaned.describe()

"""**Clustermap plots a matrix dataset as a hierarchically-clustered heatmap.**


"""

sns.clustermap(df_cleaned.corr(), cmap='viridis', col_cluster=True);

sns.pairplot(df_cleaned);
plt.suptitle('Pairplot', y=1.05);

'''
# Encode categorical variables using LabelEncoder
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns
print("\nCategorical columns identified for encoding:")
print(categorical_columns)

label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df_cleaned[col] = le.fit_transform(df_cleaned[col].astype(str))
    label_encoders[col] = le

# Scale numerical columns excluding specific ones
numerical_columns = df_cleaned.select_dtypes(include=['int64', 'float64']).columns
excluded_columns = ['id_estudiante', 'dni']
numerical_columns = [col for col in numerical_columns if col not in excluded_columns]
scaler = StandardScaler()
df_cleaned[numerical_columns] = scaler.fit_transform(df_cleaned[numerical_columns])
'''

'''

# Identify categorical columns
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns
print("\nCategorical columns identified:")
print(categorical_columns)

# Apply MCA (Multiple Correspondence Analysis) for dimensionality reduction of categorical data
print("\nApplying MCA for dimensionality reduction on categorical data:")
mca = MCA(n_components=10, random_state=42)
mca_result = mca.fit_transform(df_cleaned[categorical_columns])
#explained_inertia = mca.explained_inertia_
#print("Explained variance by MCA components:", explained_inertia)

# Combine MCA results with numerical data
numerical_columns = df_cleaned.select_dtypes(include=['int64', 'float64']).columns
numerical_data = df_cleaned[numerical_columns].reset_index(drop=True)
mca_data = pd.DataFrame(mca_result, columns=[f'MCA_{i+1}' for i in range(mca_result.shape[1])])
combined_data = pd.concat([numerical_data, mca_data], axis=1)

# Scale combined data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(combined_data)
'''

'''
# Define ordinal variables and their Likert scale mapping
ordinal_columns = [
    'cambio_dinamica_parental', 'cambio_vida_social', 'comunicación_familiares',
    'relacion_coparental_buena', 'evito_descuidar_hogar', 'pausa_estudios_cuidado_hijo',
    'considero_pausa_estudios', 'considero_dejar_estudiar', 'pendiente_hijo',
    'dedido_tiempo_tareas', 'apoyo_familiar_hijo', 'coparentalidad_cuidado',
    'esfuerzo_academico', 'procupo_menor_hijo', 'satisfaccion_resultados_academicos',
    'planifico_dia', 'planifico_tiempo_hijo', 'planifico_tiempo_tareas',
    'prioridades_diarias', 'cumplo_actividades_diarias',
    'planificacion_tiempo_hijoyacademico', 'apruebo_asignaturas',
    'ampliacion_conocimiento', 'impacto_sobrecarga', 'presento_tareas',
    'asistencia_puntual', 'abandono_clases', 'expongo_seguro',
    'impacto_rendimiento', 'satisfaccion_rendimiento'
]

likert_scale = {
    'Nunca': 0,
    'A veces': 1,
    'Casi siempre': 2,
    'Siempre': 3
}

# Map Likert scale to ordinal variables
for column in ordinal_columns:
    if column in df_cleaned.columns:
        df_cleaned[column] = df_cleaned[column].map(likert_scale)
'''


# Encode remaining categorical variables
encoders = {}
for column in df_cleaned.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df_cleaned[column] = le.fit_transform(df_cleaned[column])
    encoders[column] = le

# Apply SelectKBest for feature selection
print("\nApplying SelectKBest for feature selection")
X_selected = SelectKBest(score_func=chi2, k=10).fit_transform(df_cleaned, df_cleaned.index)
selected_features = SelectKBest(score_func=chi2, k=10).fit(df_cleaned, df_cleaned.index).get_support(indices=True)
selected_columns = df_cleaned.columns[selected_features]
print(f"Count Selected features: {len(list(selected_columns))}")
print(f"Selected features: {list(selected_columns)}")


'''
# Reduce the dataframe to selected features
selected_columns = list(selected_columns)  # Ensure it's a list for appending
if 'genero' in df_cleaned.columns and 'genero' not in selected_columns:
    selected_columns.append('genero')  # Add 'genero' column if not included
'''

df_cleaned = df_cleaned[selected_columns]

'''
print(f"Count Selected features included genero: {len(list(selected_columns))}")
print(f"Selected features: {list(selected_columns)}")
'''

# Guardar el archivo
df_cleaned.to_csv('dataset_encoded.csv', sep=';', index=False, encoding="latin1")
df_cleaned.head()

# Descargar el archivo
#files.download('dataset_encoded.csv')

# Standardize the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_cleaned)

df_scaled = pd.DataFrame(scaled_data, columns=df_cleaned.columns.tolist())

# Guardar el archivo
df_scaled.to_csv('dataset_scaled.csv', sep=';', index=False, encoding="latin1")
df_scaled.head()

# Descargar el archivo
#files.download('dataset_scaled.csv')

# Apply PCA for dimensionality reduction
pca = PCA()
pca_result = pca.fit_transform(scaled_data)
explained_variance = np.cumsum(pca.explained_variance_ratio_)

# Plot the explained variance ratio
plt.figure(figsize=(8, 5))
plt.plot(range(1, len(explained_variance) + 1), explained_variance, marker='o')
plt.title('Cumulative Explained Variance by PCA Components')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance')
plt.grid(True)
plt.show()

# Determine the optimal number of components (95% variance)
num_components = np.argmax(explained_variance >= 0.95) + 1

print(f"Numero de componentes:{num_components}")

# Reduce dimensionality to the optimal number of components
pca_optimal = PCA(n_components=num_components)
data_reduced = pca_optimal.fit_transform(scaled_data)

# Elbow Method to determine optimal number of clusters
inertia = []
silhouette_scores = []
clusters_range = range(2, 11)

for k in clusters_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(data_reduced)
    inertia.append(kmeans.inertia_)
    silhouette_scores.append(silhouette_score(data_reduced, kmeans.labels_))

# Plot Elbow Method
plt.figure(figsize=(8, 5))
plt.plot(clusters_range, inertia, marker='o')
plt.title('Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('Inertia')
plt.grid(True)
plt.show()

# Plot Silhouette Scores
plt.figure(figsize=(8, 5))
plt.plot(clusters_range, silhouette_scores, marker='o')
plt.title('Silhouette Scores')
plt.xlabel('Number of Clusters')
plt.ylabel('Silhouette Score')
plt.grid(True)
plt.show()

# Choose the optimal number of clusters (based on visual inspection, e.g., k=4)
optimal_clusters = 2

# Apply K-Means clustering with optimal clusters
kmeans = KMeans(n_clusters=optimal_clusters, random_state=42)
kmeans_clusters = kmeans.fit_predict(data_reduced)

# Evaluate K-Means Clustering
kmeans_silhouette = silhouette_score(data_reduced, kmeans_clusters)
kmeans_davies_bouldin = davies_bouldin_score(data_reduced, kmeans_clusters)
kmeans_calinski_harabasz = calinski_harabasz_score(data_reduced, kmeans_clusters)

print("\nK-Means Clustering Evaluation:")
print(f"Silhouette Score: {kmeans_silhouette:.4f}")
print(f"Davies-Bouldin Index: {kmeans_davies_bouldin:.4f}")
print(f"Calinski-Harabasz Index: {kmeans_calinski_harabasz:.4f}")

# Apply DBSCAN clustering
dbscan = DBSCAN(eps=1.5, min_samples=5)
dbscan_clusters = dbscan.fit_predict(data_reduced)

# Evaluate DBSCAN Clustering (if applicable)
if len(set(dbscan_clusters)) > 1:
    dbscan_silhouette = silhouette_score(data_reduced, dbscan_clusters)
    dbscan_davies_bouldin = davies_bouldin_score(data_reduced, dbscan_clusters)
    dbscan_calinski_harabasz = calinski_harabasz_score(data_reduced, dbscan_clusters)
    print("\nDBSCAN Clustering Evaluation:")
    print(f"Silhouette Score: {dbscan_silhouette:.4f}")
    print(f"Davies-Bouldin Index: {dbscan_davies_bouldin:.4f}")
    print(f"Calinski-Harabasz Index: {dbscan_calinski_harabasz:.4f}")
else:
    print("\nDBSCAN Clustering Evaluation: Not applicable (single cluster or noise only)")

# Apply Agglomerative Clustering
agglo = AgglomerativeClustering(n_clusters=optimal_clusters)
agglo_clusters = agglo.fit_predict(data_reduced)

# Evaluate Agglomerative Clustering
agglo_silhouette = silhouette_score(data_reduced, agglo_clusters)
agglo_davies_bouldin = davies_bouldin_score(data_reduced, agglo_clusters)
agglo_calinski_harabasz = calinski_harabasz_score(data_reduced, agglo_clusters)

print("\nAgglomerative Clustering Evaluation:")
print(f"Silhouette Score: {agglo_silhouette:.4f}")
print(f"Davies-Bouldin Index: {agglo_davies_bouldin:.4f}")
print(f"Calinski-Harabasz Index: {agglo_calinski_harabasz:.4f}")

'''
# Evaluate clustering results
kmeans_silhouette = silhouette_score(data_reduced, kmeans_clusters)
dbscan_silhouette = silhouette_score(data_reduced, dbscan_clusters) if len(set(dbscan_clusters)) > 1 else 'N/A'
agglo_silhouette = silhouette_score(data_reduced, agglo_clusters)

# Add the clusters to the original df_cleaned
df_cleaned['KMeans_Cluster'] = kmeans_clusters
df_cleaned['DBSCAN_Cluster'] = dbscan_clusters
df_cleaned['Agglo_Cluster'] = agglo_clusters

'''

# Analyze cluster characteristics
cluster_data = pd.DataFrame(data_reduced, columns=[f"PCA_{i+1}" for i in range(data_reduced.shape[1])])
cluster_data['KMeans_Cluster'] = kmeans_clusters
cluster_data['Agglomerative_Cluster'] = agglo_clusters
cluster_data['DBSCAN_Cluster'] = dbscan_clusters

# Map cluster labels to the original data
df_cleaned['KMeans_Cluster'] = kmeans_clusters
df_cleaned['Agglomerative_Cluster'] = agglo_clusters
df_cleaned['DBSCAN_Cluster'] = dbscan_clusters

# Compute descriptive statistics for original variables by K-Means clusters
kmeans_cluster_summary = df_cleaned.groupby('KMeans_Cluster').mean()
print("\nDescriptive Statistics for Original Variables by K-Means Clusters:")
print(kmeans_cluster_summary)

# Compute descriptive statistics for original variables by Agglomerative clusters
agglo_cluster_summary = df_cleaned.groupby('Agglomerative_Cluster').mean()
print("\nDescriptive Statistics for Original Variables by Agglomerative Clusters:")
print(agglo_cluster_summary)

# Compute descriptive statistics for original variables by DBSCAN clusters
if len(set(dbscan_clusters)) > 1:
    dbscan_cluster_summary = df_cleaned.groupby('DBSCAN_Cluster').mean()
    print("\nDescriptive Statistics for Original Variables by DBSCAN Clusters:")
    print(dbscan_cluster_summary)

# Visualize distributions of variables across K-Means clusters
for col in df_cleaned.columns[:-3]:  # Exclude cluster columns
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='KMeans_Cluster', y=col, data=df_cleaned)
    plt.title(f'Distribution of {col} Across K-Means Clusters')
    plt.show()

# Visualize distributions of variables across DBSCAN clusters
if len(set(dbscan_clusters)) > 1:
    for col in df_cleaned.columns[:-3]:  # Exclude cluster columns
        plt.figure(figsize=(8, 5))
        sns.boxplot(x='DBSCAN_Cluster', y=col, data=df_cleaned)
        plt.title(f'Distribution of {col} Across DBSCAN Clusters')
        plt.show()

# Visualize distributions of variables across Agglomerative clusters
for col in df_cleaned.columns[:-3]:  # Exclude cluster columns
    plt.figure(figsize=(8, 5))
    sns.boxplot(x='Agglomerative_Cluster', y=col, data=df_cleaned)
    plt.title(f'Distribution of {col} Across Agglomerative Clusters')
    plt.show()

# Visualize K-Means Clustering
plt.figure(figsize=(8, 6))
sns.scatterplot(x=data_reduced[:, 0], y=data_reduced[:, 1], hue=kmeans_clusters, palette='tab10')
plt.title('K-Means Clustering')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend(title='Cluster')
plt.grid(True)
plt.show()

# Visualize DBSCAN Clustering
if len(set(dbscan_clusters)) > 1:
    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=data_reduced[:, 0], y=data_reduced[:, 1], hue=dbscan_clusters, palette='tab10')
    plt.title('DBSCAN Clustering')
    plt.xlabel('PCA Component 1')
    plt.ylabel('PCA Component 2')
    plt.legend(title='Cluster')
    plt.grid(True)
    plt.show()

# Visualize Agglomerative Clustering
plt.figure(figsize=(8, 6))
sns.scatterplot(x=data_reduced[:, 0], y=data_reduced[:, 1], hue=agglo_clusters, palette='tab10')
plt.title('Agglomerative Clustering')
plt.xlabel('PCA Component 1')
plt.ylabel('PCA Component 2')
plt.legend(title='Cluster')
plt.grid(True)
plt.show()

# Output results
print("Cluster Distribution:")
print(df_cleaned['KMeans_Cluster'].value_counts())

# Statistical correlation analysis
correlation_results = {}
for column in df_cleaned.columns[:-3]:  # Exclude the cluster columns
    if df_cleaned[column].dtype in [np.int64, np.float64]:
        correlation, p_value = spearmanr(df_cleaned[column], df_cleaned['KMeans_Cluster'])
        correlation_results[column] = {'Correlation': correlation, 'P-Value': p_value}

# Display significant correlations
print("Significant Correlations with Clusters:")
for column, stats in correlation_results.items():
    if stats['P-Value'] < 0.05:
        print(f"{column}: Correlation = {stats['Correlation']:.2f}, P-Value = {stats['P-Value']:.4f}")

# Output results
print("K-Means Silhouette Score:", kmeans_silhouette)
print("DBSCAN Silhouette Score:", dbscan_silhouette)
print("Agglomerative Clustering Silhouette Score:", agglo_silhouette)
print("Cluster Distribution:")
print(df_cleaned['KMeans_Cluster'].value_counts())